c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

c_stdlib:
  - sysroot

c_stdlib_version:
  - "2.17"

cmake_version:
  - ">=3.26.4,!=3.30.0"

cuda_compiler:
  - cuda-nvcc

cuda11_compiler:
  - nvcc

legate_version:
  - "=25.07.*,>=0.0.0.dev0"

cupynumeric_version:
  - "=25.07.*,>=0.0.0.dev0"

rapids_version:
  - =25.04.*
