name: pr

concurrency:
  group: ci-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pull-request/[0-9]+"

env:
  # where jobs that download conda packages store the local channel
  RAPIDS_LOCAL_CONDA_CHANNEL: /tmp/local-conda-packages

jobs:

  # group together all jobs that must pass for a PR to be merged
  # (for use by branch protections)
  pr-builder:
    needs:
      - pre-commit
      - conda-python-build
      - conda-python-tests
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@branch-24.12

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1

  conda-python-build:
    needs:
      - pre-commit
    uses: ./.github/workflows/conda-python-build.yaml
    with:
      script: "ci/build_all.sh"
    secrets: inherit

  conda-python-tests:
    needs:
      - pre-commit
      - conda-python-build
    strategy:
      fail-fast: false
      # As of the last time this was updated, legate-core / cupynumeric packages were published for only:
      #
      #  * architectures: amd64 only
      #  * CUDA: >=12.2
      #  * Python: 3.10, 3.11, 3.12  (3.11 used in doc building)
      #
      # Valid set of RAPIDS ci-conda image tags: https://hub.docker.com/r/rapidsai/ci-conda/tags
      matrix:
        include:
          - ARCH: "amd64"
            CUDA_VER: "12.5.1"
            PY_VER: "3.10"
          - ARCH: "amd64"
            CUDA_VER: "12.5.1"
            PY_VER: "3.12"
    runs-on: linux-${{ matrix.ARCH }}-gpu-v100-latest-1
    container:
      image: "rapidsai/ci-conda:cuda${{ matrix.CUDA_VER }}-ubuntu22.04-py${{ matrix.PY_VER }}"
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: download conda packages
        uses: actions/download-artifact@v4
        with:
          name: legate-dataframe-conda-cuda${{ matrix.CUDA_VER }}-${{ matrix.ARCH }}-py${{ matrix.PY_VER }}
          path: ${{ env.RAPIDS_LOCAL_CONDA_CHANNEL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.run_id }}
      - name: test python and C++ interface
        run: |
          ci/test_all.sh

  docs-build:
    needs:
      - conda-python-build
    uses: ./.github/workflows/docs-build.yaml
    with:
      script: "ci/build_docs.sh"
      deploy: false
    secrets: inherit
